version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
  - dependency-name: nio4r
    versions:
    - 2.5.6
  - dependency-name: minitest
    versions:
    - 5.14.4
  - dependency-name: regexp_parser
    versions:
    - 2.1.0
