name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: ".tool-versions"

    - name: Run specs
      run: |
        bundle exec rake
