name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3'
        bundler-cache: true

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Run specs
      run: |
        bundle exec rake
